ALTER TABLE jobs ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS specialty VARCHAR(50);

ALTER TABLE jobs DROP CONSTRAINT IF EXISTS ck_jobs_category;
ALTER TABLE jobs
    ADD CONSTRAINT ck_jobs_category
        CHECK (category IN ('TECH', 'BUSINESS', 'DESIGN', 'MEDIA', 'LANGUAGE', 'OTHER'));
